### ISSUE TITLE
TEMPLATE - Checklist move adapter to iobroker-community-adapters

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/info#48]
- [ ] migrate or fork/importgithub repository to iobroker-community adapters
- [ ] add access for ex-owner (if desired)
- [ ] add a issue at old repository stating the move (if forked/imported only)
- [ ] check access to npm
- [ ] add npm owner bluefox
- [ ] add npm owner apollon77
- [ ] adapt links at package.json
- [ ] adapt owner at package.json
- [ ] adapt links at io-package.json
- [ ] adapt owner at io-package.json
- [ ] add github testing and release
- [ ] update testing to node 16/18/20
- [ ] add dependabot
- [ ] add changelog at README.md
- [ ] adapt latest repository links
- [ ] adapt stable repository links
  . 
- [ ] run adapter checker and fix issues
 .
- [ ] create a new release
 .
- [ ] check wether an maintainer is available
